# Cloudflare Workers configuration for TinyWebDB with R2
# See: https://developers.cloudflare.com/workers/wrangler/configuration/

name = "tinywebdb-r2"
main = "src/index.ts"
compatibility_date = "2025-10-22"

# R2 Bucket binding
# Create bucket: wrangler r2 bucket create tinywebdb-r2
[[r2_buckets]]
binding = "TINYWEBDB_R2"
bucket_name = "YOUR_R2_BUCKET_NAME"
