# Cloudflare Workers configuration for TinyWebDB with R2
# See: https://developers.cloudflare.com/workers/wrangler/configuration/

name = "tinywebdb-r2"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# R2 Bucket binding
# When using deploy buttons, R2 bucket will be created automatically
# For manual deployment:
#   1. wrangler r2 bucket create tinywebdb-r2
#   2. Update wrangler.toml with bucket_name
[[r2_buckets]]
binding = "TINYWEBDB_R2"
