# Cloudflare Workers configuration for TinyWebDB with D1
# See: https://developers.cloudflare.com/workers/wrangler/configuration/

name = "tinywebdb-d1"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# D1 Database binding
# When using deploy buttons, D1 database will be created automatically
# For manual deployment:
#   1. wrangler d1 create tinywebdb-d1
#   2. Update wrangler.toml with database_id
#   3. wrangler d1 execute tinywebdb-d1 --file=./src/schema.sql
[[d1_databases]]
binding = "TINYWEBDB_D1"
